<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <title>Успешная запись на услугу</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
        }
        h1 {
            text-align: center;
            color: #333;
        }
        p {
            text-align: center;
            margin-top: 20px;
            color: #666;
        }
        .success-message {
            text-align: center;
            margin-top: 20px;
            font-size: 18px;
            color: green;
        }
        a{
            color: lightpink;
            text-align: center;
        }
        a:hover{
            color:plum;
        }
    </style>
</head>
<body>
<div class="container">
    <h1>Успешная запись на услугу</h1>
    <p>Спасибо, ваша запись на услугу была успешно оформлена!</p>
    <p class="success-message">Администратор с вами свяжется</p>
    <a href="/" class="nav-link px-2 link-secondary">Перейти на вкладку "Услуги"</a>
</div>
</body>
</html>